3.8.1/specific category view
4GeeksAcademy/Proyecto-final-nikita-ximena-sofia-diana-paginaWebDeRecetas pull request #26
Opened 2024-09-05 17:51 UTC by XimenaAvalos

Hice la vista para las categorias especificas

2024-09-06 09:28 UTC, Diwoop commented
rafael nos dijo que estaria bien añadir un filtro de categorias en la vista donde salen todas, que opinas

2024-09-09 08:04 UTC, Diwoop approved these changes

2024-09-09 08:15 UTC, Diwoop requested changes
Hay que resolver los conflictos en el mismo branch, traete los cambios del main y puedes ver los conflictos en tu branch

2024-09-10 04:20 UTC, Truficop approved these changes
Todo ok, solo falta la manera de llegar a ver las categorias

2024-09-11 21:45 UTC, Truficop approved these changes

2024-09-14 11:28 UTC, closed without merging