navbar
4GeeksAcademy/Proyecto-final-nikita-ximena-sofia-diana-paginaWebDeRecetas pull request #28
Opened 2024-09-05 20:17 UTC by XimenaAvalos

He añadido los estilos al navbar

2024-09-05 23:56 UTC, Truficop requested changes

2024-09-05 23:56 UTC, Truficop commented on src/front/js/component/navbar.js
> -        )}
Las conecciones con el usuario y la navbar no borrar porfavor

2024-09-05 23:56 UTC, Truficop commented on src/front/js/component/navbar.js
> -    )}
Esto tampoco lo borres, esta parte hace falta para configurar diferentes vistas

2024-09-09 20:35 UTC, XimenaAvalos commented
Creo que no he tocado nada de la funcionalidad del navbar y agregue los estilos. por favor háganmelo saber.

2024-09-10 04:35 UTC, Truficop approved these changes

2024-09-10 04:35 UTC, merged